on: [push, pull_request]
name: Test
jobs:
  test:
    name: Go tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -race ./...
